// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/12/12 12:36:32
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/apple/Documents/code/util/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Documents/code/util/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Documents/code/util/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Documents/code/util/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Documents/code/util/src/plugins/**/*.{js,ts,mjs}","/Users/apple/Documents/code/util/src/composables/**/*.{js,ts,mjs}","/Users/apple/Documents/code/util/src/utils/**/*.{js,ts,mjs}","/Users/apple/Documents/code/util/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Documents/code/util/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Documents/code/util/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Documents/code/util/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;